include:
  - local: .gitlab-ci-windows.yml
  - local: .gitlab-ci-osd.yml

variables:
  NAME: ${GITLAB_USER_NAME}
  FULLNAME: ${GITLAB_USER_NAME}
  EMAIL: ${GITLAB_USER_EMAIL}
  GIT_AUTHOR_NAME: ${GITLAB_USER_NAME}
  GIT_COMMITTER_NAME: ${GITLAB_USER_NAME}

stages:
  - mirror
  - clone
  - install
  - build
  - test

mirror repos:
  stage: mirror
  variables:
    ENVIRONMENT: mirror
  trigger: 
    project: robotframework-aio/main/ci-mirroring
    strategy: depend

.build-version:
  variables:
    RobotFrameworkVersion: 'dev'
  # rules:
  #   - if: $CI_COMMIT_TAG =~ /^rel\/(\d+\.\d+\.\d+(?:\.\d+)?)$/
  #     variables: 
  #       RobotFrameworkVersion: $(echo $CI_COMMIT_TAG | sed -e "s/rel\///g")
  #   - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  #     variables:
  #       RobotFrameworkVersion: $(echo merged_$CI_COMMIT_REF_NAME | sed -e "s/\//-/g")
  #   - if: $CI_COMMIT_REF_NAME
  #     variables:
  #       RobotFrameworkVersion: $(echo dev_$CI_COMMIT_REF_NAME | sed -e "s/\//-/g")