windows:clone:
  stage: clone
  needs: ["mirror repos"]
  tags: 
    - windows
  script:
    - echo "Cloning/Updating repositories"
    - bash ./cloneall

windows:install:
  stage: install
  needs: ["windows:clone"]
  # dependencies: []
  #   - windows:clone:
  tags: 
    - windows
  script:
    - echo "Installing python and VsCode ..."
    - bash ./wget/install_via_cntlm.sh
  # cache:
  #   paths:
  #     - download/
  #     - config/

windows:build:
  extends: .build-version
  needs: ["windows:install"]
  # dependencies:
  #   - windows:install
  stage: build
  tags:
    - windows
  script:
    - echo "Building Windows Installer package ..."
    - bash ./build
  artifacts:
    name: $RobotFrameworkVersion
    paths:
      - Output/

windows:selftest:
  stage: test
  needs: ["windows:build"]
  # dependencies:
  #   - build:windows
  tags:
    - windows
  script:
    - echo "Selftest for Windows"
    # - 'dir env:'
  when: manual
